### ISSUE TITLE
Repeating old cards while not showing new

### ISSUE THREAD

**Issue by Darksonn** [ticki/mu#1]
When running `mu`, it keeps cycling between a few cards, even though I already reviewed them a minute before, while there is still a new card I have not yet seen.

```yaml
---
metacards:
  - id: sum-function-holomorphic
    state: Learnt
    current_interval:
      secs: 259200
    due: "2019-09-26T16:59:21.086852181Z"
    history:
      - time: "2019-09-22T18:52:38.243912608Z"
        due: "2019-09-22T18:47:50.079722702Z"
        score: Good
        ended_interval:
          secs: 0
        state_before: New
        ease_before: 2.5
      - time: "2019-09-23T16:58:28.901720619Z"
        due: "2019-09-24T18:52:38.243912608Z"
        score: Okay
        ended_interval:
          secs: 172800
        state_before:
          Learning: 0
        ease_before: 2.5
      - time: "2019-09-23T16:59:21.086852181Z"
        due: "2019-09-25T16:58:28.901720619Z"
        score: Okay
        ended_interval:
          secs: 172800
        state_before:
          Learning: 1
        ease_before: 2.5
    ease: 2.5
  - id: closed-staircase-implies-primitive
    state: Learnt
    current_interval:
      secs: 259200
    due: "2019-09-26T16:58:47.879997392Z"
    history:
      - time: "2019-09-22T18:59:03.654474189Z"
        due: "2019-09-22T18:47:50.079726359Z"
        score: Okay
        ended_interval:
          secs: 0
        state_before: New
        ease_before: 2.5
      - time: "2019-09-23T16:52:21.953627033Z"
        due: "2019-09-23T18:59:03.654474189Z"
        score: Okay
        ended_interval:
          secs: 86400
        state_before:
          Learning: 0
        ease_before: 2.5
      - time: "2019-09-23T16:58:47.879997392Z"
        due: "2019-09-25T16:52:21.953627033Z"
        score: Okay
        ended_interval:
          secs: 172800
        state_before:
          Learning: 1
        ease_before: 2.5
    ease: 2.5
  - id: goursats-lemma
    state: New
    current_interval:
      secs: 0
    due: "2019-09-22T18:47:50.079728379Z"
    history: []
    ease: 2.5
  - id: sigma-algebra
    state: Learnt
    current_interval:
      secs: 897480
    due: "2019-10-04T02:17:38.356087624Z"
    history:
      - time: "2019-09-22T19:22:23.920702234Z"
        due: "2019-09-22T18:47:50.079730790Z"
        score: Fail
        ended_interval:
          secs: 0
        state_before: New
        ease_before: 2.5
      - time: "2019-09-23T16:54:08.996178374Z"
        due: "2019-09-23T19:22:23.920702234Z"
        score: Easy
        ended_interval:
          secs: 86400
        state_before:
          Learning: 0
        ease_before: 2.5
      - time: "2019-09-23T16:59:38.356087624Z"
        due: "2019-09-26T16:54:08.996178374Z"
        score: Easy
        ended_interval:
          secs: 259200
        state_before: Learnt
        ease_before: 2.5
    ease: 2.6500000953674318
statistics:
  reviews:
    - Good
    - Okay
    - Fail
    - Okay
    - Easy
    - Okay
    - Okay
    - Okay
    - Easy
  activity:
    2019-09-23: 6
    2019-09-22: 3
  adaptive_retention_rate: 0.8508182168006897
  familiarity: 1.3000000715255738
tag_statistics:
  Fact:
    reviews:
      - Fail
      - Easy
      - Easy
    activity:
      2019-09-23: 2
      2019-09-22: 1
    adaptive_retention_rate: 0.8054224848747253
    familiarity: 0.6999999284744263
  Noncourse:
    reviews:
      - Fail
      - Easy
      - Easy
    activity:
      2019-09-22: 1
      2019-09-23: 2
    adaptive_retention_rate: 0.8054224848747253
    familiarity: 0.6999999284744263
  ComplexAnalysis:
    reviews:
      - Good
      - Okay
      - Okay
      - Okay
      - Okay
      - Okay
    activity:
      2019-09-23: 4
      2019-09-22: 2
    adaptive_retention_rate: 0.8639329075813294
    familiarity: 1.6000001430511475
  Theorem:
    reviews:
      - Good
      - Okay
      - Okay
      - Okay
      - Okay
      - Okay
    activity:
      2019-09-23: 4
      2019-09-22: 2
    adaptive_retention_rate: 0.8639329075813294
    familiarity: 1.6000001430511475
updated: "2019-09-22T18:47:50.079731295Z"
new_today: 0
```
